import pandas as pd
df_eye_feature = pd.read_csv('./output/eyeFeatures.csv')
df_mouth_feature = pd.read_csv('./output/mouthFeatures.csv')
df_groundtruth = pd.read_csv('./groundtruth/ground_truth.csv')
df_train = pd.merge(df_eye_feature, df_mouth_feature, on='Video')
df_train = pd.merge(df_train, df_groundtruth, on='Video')
df_train.dropna(inplace=True)
df_train = df_train.sample(frac=1).reset_index(drop=True)
print(df_train)
df_train.to_csv('./output/training_set.csv', index=False)